trigger:
  - develop

pr:
  - develop
  - main

pool:
  name: Default

resources:
  repositories:
    - repository: templates
      type: github
      name: securancy/azure-pipeline-templates
      endpoint: securancy

extends:
  template: pnpm.yml@templates
  parameters:
    nodeVersion: '20.x'
    buildScript: 'build'
    outputFolder: 'dist'
    runtimeStack: 'NODE|20-lts'
    appPath: './movie-showcase/'    
    webAppName: 'movie-showcase'
    azureSubscription: 'Azure | Securancy Intelligence | movie-showcase'
    environment: 'Development'    
    moveToOutput:
      - ./movie-showcase/package.json
      - ./movie-showcase/node_modules
    
